Repository kwizapp/poster-service, pull requests merged in 2020-05, with the labels that each got.

#42 📚 Documentation updates
  README.md
  src/index.js
Labels: documentation

#43 Update link to the API in the wiki
  README.md
Labels: documentation

#44 Separate production and staging environments
  .github/workflows/main.yml
Labels: devops

#46 Add release-drafter action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: devops

#48 Release v1.0.1
  package-lock.json
  package.json
Labels: coordination

#49 📝 add repo structure to README
  README.md
Labels: documentation

#50 Release v1.0.2
  README.md
Labels: coordination
